# Generated by Django 3.2.8 on 2022-02-14 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('price', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_products', to='shop.product')),
            ],
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_quantity', models.PositiveIntegerField(default=0)),
                ('total_price', models.PositiveIntegerField(default=0)),
                ('products', models.ManyToManyField(related_name='products', to='cart.CardProduct')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism familiya')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=80, verbose_name='Manzil')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('payed', models.BooleanField(default=False, verbose_name="To'lov xolati")),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.cart')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familya')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon')),
                ('telegram_id', models.CharField(blank=True, max_length=50, verbose_name='Telegram ID')),
                ('email', models.EmailField(max_length=254)),
                ('state', models.CharField(max_length=80, verbose_name='Viloyat')),
                ('address', models.CharField(max_length=80, verbose_name='Tuman')),
                ('street', models.CharField(max_length=150, verbose_name="Ko'cha va uy manzili")),
                ('postal_code', models.CharField(max_length=50, verbose_name='Pochta indeksi')),
                ('payment_method', models.CharField(max_length=50, verbose_name="To'lov turi")),
                ('message', models.TextField(blank=True, verbose_name="Qo'shimcha xabar")),
                ('payed', models.BooleanField(default=False, verbose_name="To'lov xolati")),
                ('products', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cart.order')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Xaridor')),
            ],
            options={
                'verbose_name': 'Buyurtma Tovar',
                'verbose_name_plural': 'Buyurtma Tovarlar',
                'ordering': ['-id'],
            },
        ),
    ]
